spring.datasource.url=jdbc:postgresql://localhost:5432/jobdb
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

app.upload.path=C:/upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.jwt.issuer = com.dev.anh.job.demo
app.jwt.access-life = 3
app.jwt.refresh-life = 7

spring.mvc.format.date=yyyy-MM-dd
spring.mvc.format.time=HH:mm
spring.mvc.format.date-time=yyyy-MM-dd HH:mm